# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          name: custompool
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'acrmahesh'
            repository: 'custom2aksnginxapp1'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
              $(Build.SourceVersion)
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/Git-Repository-files/kube-manifests'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            targetPath: '$(Pipeline.Workspace)'
  - stage: Deploy  
    displayName: Deploy Stage  
    jobs:
      - job: Deploy
        displayName: Deploy Job
        pool:
          name: custompool
        steps: 
        
        - task: KubernetesManifest@1
          inputs:
            action: 'createSecret'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'dev-ns-k8s-aks-svc-conn'
            namespace: 'dev'
            secretType: 'dockerRegistry'
            secretName: 'dev-aksdevopsacr-secret'
            dockerRegistryEndpoint: 'acrmahesh'
        
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'dev-ns-k8s-aks-svc-conn'
            namespace: 'dev'
            manifests: '$(Pipeline.Workspace)'
            #containers: 'acrmahesh.azurecr.io/custom2aksnginxapp1/$(Build.BuildId)'
            imagePullSecrets: 'dev-aksdevopsacr-secret'

